name: restaurent_digital_menu
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_crashlytics: ^4.0.4
  cupertino_icons: ^1.0.6
  #Statemanagement
  flutter_hooks: ^0.20.5

  #Statemanagement and trigger obeservers bloc
  flutter_bloc: ^8.1.5

  #internationalizing and localization
  #flutter pub run easy_localization:generate --source-dir ./assets/translations
  #dart pub run easy_localization:generate -S assets/translations -f keys -O lib/generated -o locale_keys.g.dart
  easy_localization: ^3.0.7

#  #adapting screen and font size
#  flutter_screenutil: ^5.9.1

  # parses SVG files
  vector_graphics: ^1.1.11+1

  # A package for creating dynamic forms in your Flutter app.
  flutter_form_builder: ^9.3.0

  # Dependency Injection service locator
  injectable: ^2.3.0

  # widget can help you bring simple yet beautiful skeleton loaders
  shimmer_animation: ^2.1.0+1

  # Dependency Injection service locator
  get_it: ^7.6.0

  # Functional error handling in flutter
  multiple_result: ^5.1.0

  # a package containing annotations for freezed.
  freezed_annotation: ^2.4.1

  # Code generator package for freezed
  freezed: ^2.5.2

  # Generating code for JSON serialization and deserialization.
  json_annotation: ^4.9.0

  # Code generator package for Dart projects which allows you to easily serialize JSON objects.
  json_serializable: ^6.8.0

  # Used to make HTTP requests
  dio: ^5.3.3

  # Dio interceptor that logs network calls in a pretty, easy to read format
  pretty_dio_logger: ^1.3.1

  #Loading animation
  loading_animation_widget: ^1.2.1

  #Load configuration at runtime from a .env file which can be used throughout the application
  flutter_dotenv: ^5.1.0

  # extensible logger which prints beautiful logs.
  logger: ^2.3.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0
  lottie: ^3.1.2
  fluttertoast: ^8.2.6
  awesome_notifications: ^0.9.3+1
  # for splash screen
  flutter_native_splash: ^2.3.5
  go_router: ^14.2.3

  #adapting screen and font size
  responsive_sizer: ^3.3.1
  beamer: ^1.6.1
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_test:
    sdk: flutter
  # Build Runner is a package that provides a concrete way of generating files using Dart code, outside of tools like pub and the Dart VM.
  # Use the below command to generate files:
  # `dart run build_runner build --delete-conflicting-outputs`
  build_runner: ^2.4.11
  # Injectable Generator is a generator for injectable.
  injectable_generator: ^2.4.0
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/png/app_logo.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21

  web:
    generate: true
    image_path: "assets/images/png/app_logo.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/translations/
    - assets/images/icons/
    - assets/images/png/

  fonts:
    - family: ARIAL
      fonts:

        - asset: assets/fonts/ARIALLGT.ttf
          weight: 300
        - asset: assets/fonts/ARIAL.ttf
          weight: 400
        - asset: assets/fonts/ArialMdm.ttf
          weight: 500
        - asset: assets/fonts/ARIALBD.ttf
          weight: 700
        - asset: assets/fonts/ARIBLK.ttf
          weight: 800
